# Generated by Django 3.2.16 on 2022-11-25 12:57

from django.db import migrations


def forwards_func(apps, schema_editor):
    # Get model
    
    Cours = apps.get_model("mainapp", "Courses")
    # Create model's objects
    Cours.objects.create(
        name = "Go",
        description = "На курсе Go Вы изучите основы языка GO.",
        description_as_markdown = True,
        cost = "6560.66",
        cover = "img/course006.jpg",
        created = "2021-07-11T08:39:15.369Z",
        updated = "2021-07-11T09:07:04.253Z",
    )


    Teacher = apps.get_model("mainapp", "CourseTeachers")
    # Create model's objects
    Teacher.objects.create(
        name_first = "Alis",
        name_second = "Petrova",
        day_birth = "1975-01-07",
        #course = [
        #  6,
        #  8
        #]
    )


def reverse_func(apps, schema_editor):
    # Get model
    Cours = apps.get_model("mainapp", "Courses")
    Teacher = apps.get_model("mainapp", "CourseTeachers")
    Lesson_my = apps.get_model("mainapp", "Lesson")
    
    # Delete objects
    Cours.objects.all().delete()
    Teacher.objects.all().delete()
    Lesson_my.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_data_migration"),
        
    ]


    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
